In [ ]:

from tkinter import *
from tkinter import messagebox
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score

l1=['itching','skin_rash','nodal_skin_eruptions','continuous_sneezing','shivering','chills','joint_pain',
    'stomach_pain','acidity','ulcers_on_tongue','muscle_wasting','vomiting','burning_micturition','spotting_ urination','fatigue',
    'weight_gain','anxiety','cold_hands_and_feets','mood_swings','weight_loss','restlessness','lethargy','patches_in_throat',
    'irregular_sugar_level','cough','high_fever','sunken_eyes','breathlessness','sweating','dehydration','indigestion',
    'headache','yellowish_skin','dark_urine','nausea','loss_of_appetite','pain_behind_the_eyes','back_pain','constipation',
    'abdominal_pain','diarrhoea','mild_fever','yellow_urine','yellowing_of_eyes','acute_liver_failure','fluid_overload',
    'swelling_of_stomach','swelled_lymph_nodes','malaise','blurred_and_distorted_vision','phlegm','throat_irritation',
    'redness_of_eyes','sinus_pressure','runny_nose','congestion','chest_pain','weakness_in_limbs','fast_heart_rate',
    'pain_during_bowel_movements','pain_in_anal_region','bloody_stool','irritation_in_anus','neck_pain','dizziness','cramps',
    'bruising','obesity','swollen_legs','swollen_blood_vessels','puffy_face_and_eyes','enlarged_thyroid','brittle_nails',
    'swollen_extremeties','excessive_hunger','extra_marital_contacts','drying_and_tingling_lips','slurred_speech','knee_pain','hip_joint_pain',
    'muscle_weakness','stiff_neck','swelling_joints','movement_stiffness','spinning_movements','loss_of_balance','unsteadiness','weakness_of_one_body_side',
    'loss_of_smell','bladder_discomfort','foul_smell_of urine','continuous_feel_of_urine','passage_of_gases','internal_itching','toxic_look_(typhos)',
    'depression','irritability','muscle_pain','altered_sensorium','red_spots_over_body','belly_pain','abnormal_menstruation','dischromic _patches',
    'watering_from_eyes','increased_appetite','polyuria','family_history','mucoid_sputum','rusty_sputum','lack_of_concentration','visual_disturbances',
    'receiving_blood_transfusion','receiving_unsterile_injections','coma','stomach_bleeding','distention_of_abdomen','history_of_alcohol_consumption',
    'fluid_overload','blood_in_sputum','prominent_veins_on_calf','palpitations','painful_walking','pus_filled_pimples','blackheads','scurring','skin_peeling',
    'silver_like_dusting','small_dents_in_nails','inflammatory_nails','blister','red_sore_around_nose','yellow_crust_ooze']

disease=['Fungal infection','Allergy','GERD','Chronic cholestasis','Drug Reaction',
        'Peptic ulcer diseae','AIDS','Diabetes','Gastroenteritis','Bronchial Asthma','Hypertension',
        ' Migraine','Cervical spondylosis',
        'Paralysis (brain hemorrhage)','Jaundice','Malaria','Chicken pox','Dengue','Typhoid','hepatitis A',
'Hepatitis B','Hepatitis C','Hepatitis D','Hepatitis E','Alcoholic hepatitis','Tuberculosis',
'Common Cold','Pneumonia','Dimorphic hemmorhoids(piles)',
'Heartattack','Varicoseveins','Hypothyroidism','Hyperthyroidism','Hypoglycemia','Osteoarthristis',
'Arthritis','(vertigo) Paroymsal  Positional Vertigo','Acne','Urinary tract infection','Psoriasis',
'Impetigo']
specialists = [
    "Dermatologist or Infectious Disease Specialist",  # Fungal infection
    "Allergist/Immunologist",  # Allergy
    "Gastroenterologist",  # GERD
    "Hepatologist",  # Chronic cholestasis
    "Allergist/Immunologist or Dermatologist",  # Drug Reaction
    "Gastroenterologist",  # Peptic ulcer disease
    "Infectious Disease Specialist",  # AIDS
    "Endocrinologist",  # Diabetes
    "Gastroenterologist",  # Gastroenteritis
    "Pulmonologist or Allergist/Immunologist",  # Bronchial Asthma
    "Cardiologist",  # Hypertension
    "Neurologist",  # Migraine
    "Orthopedic Surgeon or Neurologist",  # Cervical spondylosis
    "Neurologist or Neurosurgeon",  # Paralysis (brain hemorrhage)
    "Hepatologist",  # Jaundice
    "Infectious Disease Specialist",  # Malaria
    "Infectious Disease Specialist or Pediatrician",  # Chicken pox
    "Infectious Disease Specialist",  # Dengue
    "Infectious Disease Specialist",  # Typhoid
    "Hepatologist",  # Hepatitis A
    "Hepatologist",  # Hepatitis B
    "Hepatologist",  # Hepatitis C
    "Hepatologist",  # Hepatitis D
    "Hepatologist",  # Hepatitis E
    "Hepatologist",  # Alcoholic hepatitis
    "Infectious Disease Specialist or Pulmonologist",  # Tuberculosis
    "Primary Care Physician or Family Medicine Specialist",  # Common Cold
    "Pulmonologist or Infectious Disease Specialist",  # Pneumonia
    "Colorectal Surgeon or Gastroenterologist",  # Dimorphic hemorrhoids (piles)
    "Cardiologist",  # Heart attack
    "Vascular Surgeon",  # Varicose veins
    "Endocrinologist",  # Hypothyroidism
    "Endocrinologist",  # Hyperthyroidism
    "Endocrinologist",  # Hypoglycemia
    "Rheumatologist or Orthopedic Surgeon",  # Osteoarthritis
    "Rheumatologist",  # Arthritis
    "Neurologist or Otolaryngologist (ENT)",  # (Vertigo) Paroxysmal Positional Vertigo
    "Dermatologist",  # Acne
    "Urologist",  # Urinary tract infection
    "Dermatologist",  # Psoriasis
    "Dermatologist or Infectious Disease Specialist"  # Impetigo
]


l2=[]
for x in range(0,len(l1)):
    l2.append(0)

# TESTING DATA
tr=pd.read_csv("Testing.csv")
tr.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
'Migraine':11,'Cervical spondylosis':12,
'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
'(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
'Impetigo':40}},inplace=True)

X_test= tr[l1]
y_test = tr[["prognosis"]]
np.ravel(y_test)

# TRAINING DATA
df=pd.read_csv("Training.csv")

df.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
'Migraine':11,'Cervical spondylosis':12,
'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
'(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
'Impetigo':40}},inplace=True)

X= df[l1]

y = df[["prognosis"]]
np.ravel(y)

def message():
    if (Symptom1.get() == "None" and  Symptom2.get() == "None" and Symptom3.get() == "None" and Symptom4.get() == "None" and Symptom5.get() == "None"):
        messagebox.showinfo("OPPS!!", "ENTER  SYMPTOMS PLEASE")
    else :
        NaiveBayes()
        RandomForest()
        DecisionTree()

def DecisionTree():
        from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
        from sklearn import tree

        clf3 = tree.DecisionTreeClassifier() 
        clf3 = clf3.fit(X,y)
        y_pred=clf3.predict(X_test)
        print("Decision Tree")
        print(cross_val_score(y_test, y_pred))
        print("Accuracy")
        print(accuracy_score(y_test, y_pred))
        print(accuracy_score(y_test, y_pred,normalize=False))
        print("Confusion matrix")
        conf_matrix=confusion_matrix(y_test,y_pred)
        print(conf_matrix)

        psymptoms = [Symptom1.get(), Symptom2.get(), Symptom3.get(), Symptom4.get(), Symptom5.get()]

        for k in range(0, len(l1)):
            l2[k] = 1 if l1[k] in psymptoms else 0

        inputtest = pd.DataFrame([l2], columns=l1)
        predict = clf3.predict(inputtest)
        predicted = predict[0]
        h = 'no'
        for a in range(0, len(disease)):
            if disease[predicted] == disease[a]:
                h = 'yes'
                break

        if h == 'yes':
            t5.delete("1.0", END)
            t5.insert(END, disease[a])
            t8.insert(END,specialists[a])
        else:
            t5.delete("1.0", END)
            t5.insert(END, "No Disease")
def NaiveBayes():
    from sklearn.naive_bayes import MultinomialNB
    gnb = MultinomialNB()
    gnb = gnb.fit(X, np.ravel(y))
    from sklearn.metrics import accuracy_score
    y_pred = gnb.predict(X_test)
    print(accuracy_score(y_test, y_pred))
    print(accuracy_score(y_test, y_pred, normalize=False))

    psymptoms = [Symptom1.get(), Symptom2.get(), Symptom3.get(), Symptom4.get(), Symptom5.get()]

    for k in range(0, len(l1)):
        l2[k] = 1 if l1[k] in psymptoms else 0

    inputtest = pd.DataFrame([l2], columns=l1)
    predict = gnb.predict(inputtest)
    predicted = predict[0]

    h = 'no'
    for a in range(0, len(disease)):
        if disease[predicted] == disease[a]:
            h = 'yes'
            break

    if h == 'yes':
        t3.delete("1.0", END)
        t3.insert(END, disease[a])
        t6.insert(END,specialists[a])
    else:
        t3.delete("1.0", END)
        t3.insert(END, "No Disease")


def RandomForest():
    from sklearn.ensemble import RandomForestClassifier
    clf4 = RandomForestClassifier(n_estimators=100)
    clf4 = clf4.fit(X, np.ravel(y))

    # calculating accuracy 
    from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
    y_pred = clf4.predict(X_test)
    print("Random Forest")
    print("Accuracy")
    print(accuracy_score(y_test, y_pred))
    print(accuracy_score(y_test, y_pred, normalize=False))
    print("Confusion matrix")
    conf_matrix = confusion_matrix(y_test, y_pred)
    print(conf_matrix)

    psymptoms = [Symptom1.get(), Symptom2.get(), Symptom3.get(), Symptom4.get(), Symptom5.get()]

    for k in range(0, len(l1)):
        l2[k] = 1 if l1[k] in psymptoms else 0

    inputtest = pd.DataFrame([l2], columns=l1)
    predict = clf4.predict(inputtest)
    predicted = predict[0]
    h = 'no'
    for a in range(0, len(disease)):
        if disease[predicted] == disease[a]:
            h = 'yes'
            break

    if h == 'yes':
        t4.delete("1.0", END)
        t4.insert(END, disease[a])
        t7.insert(END,specialists[a])
    else:
        t4.delete("1.0", END)
        t4.insert(END, "No Disease")


root = Tk()
root.title(" Disease Prediction From Symptoms")
root.configure(bg='lightgreen')

Symptom1 = StringVar()
Symptom1.set(None)
Symptom2 = StringVar()
Symptom2.set(None)
Symptom3 = StringVar()
Symptom3.set(None)
Symptom4 = StringVar()
Symptom4.set(None)
Symptom5 = StringVar()
Symptom5.set(None)

w2 = Label(root, justify=LEFT, text=" Disease Prediction From Symptoms ")
w2.config(font=("Elephant", 30))
w2.grid(row=1, column=0, columnspan=2, padx=100)

NameLb1 = Label(root, text="")
NameLb1.config(font=("Elephant", 20))
NameLb1.grid(row=5, column=1, pady=10,  sticky=W)

S1Lb = Label(root,  text="Symptom 1")
S1Lb.config(font=("Elephant", 15))
S1Lb.grid(row=7, column=1, pady=10 , sticky=W)

S2Lb = Label(root,  text="Symptom 2")
S2Lb.config(font=("Elephant", 15))
S2Lb.grid(row=8, column=1, pady=10, sticky=W)

S3Lb = Label(root,  text="Symptom 3")
S3Lb.config(font=("Elephant", 15))
S3Lb.grid(row=9, column=1, pady=10, sticky=W)

S4Lb = Label(root,  text="Symptom 4")
S4Lb.config(font=("Elephant", 15))
S4Lb.grid(row=10, column=1, pady=10, sticky=W)

S5Lb = Label(root,  text="Symptom 5")
S5Lb.config(font=("Elephant", 15))
S5Lb.grid(row=11, column=1, pady=10, sticky=W)

lr = Button(root, text="Predict",height=1, width=20, command=message)
lr.config(font=("Elephant", 15))
lr.grid(row=15, column=1)

lr = Button(root, text="naiveBayes",height=1, width=10)
lr.config(font=("Elephant", 15))
lr.grid(row=18, column=0)

lr = Button(root, text="randomForest",height=1, width=10)
lr.config(font=("Elephant", 15))
lr.grid(row=20, column=0)

lr = Button(root, text="DecisionTree",height=1, width=10)
lr.config(font=("Elephant", 15))
lr.grid(row=22, column=0)

OPTIONS = sorted(l1)

S1En = OptionMenu(root, Symptom1,*OPTIONS)
S1En.grid(row=7, column=2)

S2En = OptionMenu(root, Symptom2,*OPTIONS)
S2En.grid(row=8, column=2)

S3En = OptionMenu(root, Symptom3,*OPTIONS)
S3En.grid(row=9, column=2)

S4En = OptionMenu(root, Symptom4,*OPTIONS)
S4En.grid(row=10, column=2)

S5En = OptionMenu(root, Symptom5,*OPTIONS)
S5En.grid(row=11, column=2)

NameLb = Label(root, text="")
NameLb.config(font=("Elephant", 20))
NameLb.grid(row=13, column=1, pady=10,  sticky=W)

NameLb = Label(root, text="")
NameLb.config(font=("Elephant", 15))
NameLb.grid(row=18, column=1, pady=10,  sticky=W)

t3 = Text(root, height=1, width=20)
t3.config(font=("Elephant", 20))
t3.grid(row=18, column=1 , padx=10)

t4 = Text(root, height=1, width=20)
t4.config(font=("Elephant", 20))
t4.grid(row=20, column=1 , padx=10)

t5 = Text(root, height=1, width=20)
t5.config(font=("Elephant", 20))
t5.grid(row=22, column=1 , padx=10)

t6 = Text(root, height=1, width=20)
t6.config(font=("Elephant", 20))
t6.grid(row=18, column=2 , padx=10)

t7 = Text(root, height=1, width=20)
t7.config(font=("Elephant", 20))
t7.grid(row=20, column=2 , padx=10)

t8 = Text(root, height=1, width=20)
t8.config(font=("Elephant", 20))
t8.grid(row=22, column=2 , padx=10)

root.mainloop()


C:\Users\B.praveen\AppData\Local\Temp\ipykernel_14440\1929718787.py:88: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  tr.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
C:\Users\B.praveen\AppData\Local\Temp\ipykernel_14440\1929718787.py:105: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,


1.0
41
Random Forest
Accuracy
1.0
41
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Decision Tree


Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\B.praveen\AppData\Local\Temp\ipykernel_14440\1929718787.py", line 126, in message
    DecisionTree()
  File "C:\Users\B.praveen\AppData\Local\Temp\ipykernel_14440\1929718787.py", line 136, in DecisionTree
    print(cross_val_score(y_test, y_pred))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 513, in cross_val_score
    scorer = check_scoring(estimator, scoring=scoring)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 474, in check_scoring
    raise TypeError(
TypeError: estimator should be an estimator implementing 'fit' method,     prognosis
0           0
1           1
2           2
3   